[package]
name = "evergreen_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.15"
bevy_log = "0.15"
variadics_please = "1.1"
bevy_egui = "0.31"
egui = "0.29"

[dev-dependencies]
bevy = "0.15"